1,$s:OptIJavaAtomType:IJavaOptAtomType:g
1,$s:ReqIJavaAtomType:IJavaReqAtomType:g
1,$s:OptBuffJavaAtomType:BuffJavaOptAtomType:g
1,$s:ReqBuffJavaAtomType:BuffJavaReqAtomType:g
1,$s:OptJpaJavaAtomType:JpaJavaOptAtomType:g
1,$s:ReqJpaJavaAtomType:JpaJavaReqAtomType:g
1,$s:OptIJavaProtAtomType:IJavaOptAtomType:g
1,$s:ReqIJavaProtAtomType:IJavaReqAtomType:g
1,$s:OptBuffJavaProtAtomType:BuffJavaProtOptAtomType:g
1,$s:ReqBuffJavaProtAtomType:BuffJavaProtReqAtomType:g
1,$s:OptJpaJavaProtAtomType:JpaJavaProtOptAtomType:g
1,$s:ReqJpaJavaProtAtomType:JpaJavaProtReqAtomType:g
1,$s:OptIJavaPubAtomType:IJavaOptAtomType:g
1,$s:ReqIJavaPubAtomType:IJavaReqAtomType:g
1,$s:OptBuffJavaPubAtomType:BuffJavaPubOptAtomType:g
1,$s:ReqBuffJavaPubAtomType:BuffJavaPubReqAtomType:g
1,$s:OptJpaJavaPubAtomType:JpaJavaPubOptAtomType:g
1,$s:ReqJpaJavaPubAtomType:JpaJavaPubReqAtomType:g
w
q

